# Encodding(8) Aassignment 

In [47]:
import pandas as pd

In [48]:
insurance_df = pd.read_csv("insurance.csv")
insurance_df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [49]:
insurance_labelencoded = insurance_df.copy()
insurance_labelencoded_loop = insurance_df.copy()
insurance_onehotencoded = insurance_df.copy()
insurance_ordinal = insurance_df.copy()

## Label Encoder without `loop`

In [50]:
from sklearn.preprocessing import LabelEncoder

In [51]:
led = LabelEncoder()

In [52]:
led.fit_transform(insurance_labelencoded["sex"])

array([0, 1, 1, ..., 0, 0, 0])

In [53]:
insurance_labelencoded.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [54]:
insurance_labelencoded["sex"] = led.fit_transform(insurance_labelencoded["sex"])
insurance_labelencoded.head()

age  sex     bmi  children smoker     region      charges
0   19    0  27.900         0    yes  southwest  16884.92400
1   18    1  33.770         1     no  southeast   1725.55230
2   28    1  33.000         3     no  southeast   4449.46200
3   33    1  22.705         0     no  northwest  21984.47061
4   32    1  28.880         0     no  northwest   3866.85520

In [55]:
insurance_labelencoded["smoker"] = led.fit_transform(insurance_labelencoded["smoker"])
insurance_labelencoded.head()

age  sex     bmi  children  smoker     region      charges
0   19    0  27.900         0       1  southwest  16884.92400
1   18    1  33.770         1       0  southeast   1725.55230
2   28    1  33.000         3       0  southeast   4449.46200
3   33    1  22.705         0       0  northwest  21984.47061
4   32    1  28.880         0       0  northwest   3866.85520

In [56]:
insurance_labelencoded["region"].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [57]:
insurance_labelencoded["region"] = led.fit_transform(insurance_labelencoded["region"])
insurance_labelencoded.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

## Perfoming encoding using loop on condition

In [58]:
from pandas.core.dtypes.common import is_numeric_dtype, is_categorical_dtype

In [59]:
insurance_labelencoded_loop.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [60]:
for column in insurance_labelencoded_loop.columns:
    if is_numeric_dtype(insurance_labelencoded_loop[column]):
        continue
    else:
        insurance_labelencoded_loop[column] = led.fit_transform(insurance_labelencoded_loop[column])

insurance_labelencoded_loop.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [61]:
is_categorical_dtype(insurance_df['sex'])

False

## Onehot encoding using pandas

In [62]:
insurance_oh_pandas = insurance_df.copy()
insurance_oh_pandas.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [63]:
pd.get_dummies(insurance_oh_pandas["sex"], prefix="sex", drop_first=True)

sex_male
0        False
1         True
2         True
3         True
4         True
...        ...
1333      True
1334     False
1335     False
1336     False
1337     False

[1338 rows x 1 columns]

## Onehot encoding `sklearn`

In [64]:
from sklearn.preprocessing import OneHotEncoder

In [65]:
ohed = OneHotEncoder(handle_unknown="ignore", drop="first")

In [66]:
insurance_onehotencoded["sex"].shape

(1338,)

In [67]:
insurance_onehotencoded["sex"].values.reshape(-1,1).shape

(1338, 1)

In [68]:
ohed.fit_transform(insurance_onehotencoded["sex"].values.reshape(-1,1)).toarray()

array([[0.],
       [1.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [69]:
ohed.categories_

[array(['female', 'male'], dtype=object)]

In [70]:
ohed.fit_transform(insurance_onehotencoded["smoker"].values.reshape(-1,1)).toarray()

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [1.]])

In [71]:
ohed.categories_

[array(['no', 'yes'], dtype=object)]

In [72]:
ohed.fit_transform(insurance_onehotencoded[["sex", "smoker", "region"]]).toarray()

array([[0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.]])

In [73]:
ohed_array = ohed.fit_transform(insurance_onehotencoded[["sex", "smoker", "region"]]).toarray()
ohed_array

array([[0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.]])

In [74]:
ohed.categories_

[array(['female', 'male'], dtype=object),
 array(['no', 'yes'], dtype=object),
 array(['northeast', 'northwest', 'southeast', 'southwest'], dtype=object)]

In [75]:
import numpy as np

In [76]:
features = ohed.categories_
features

[array(['female', 'male'], dtype=object),
 array(['no', 'yes'], dtype=object),
 array(['northeast', 'northwest', 'southeast', 'southwest'], dtype=object)]

In [77]:
features_lst = []
for i in features:
    for j in i[1:]:
        features_lst.append(j)
features_lst

['male', 'yes', 'northwest', 'southeast', 'southwest']

In [78]:
oh_encoded_features = pd.DataFrame(ohed_array, columns=features_lst)
oh_encoded_features.head()

male  yes  northwest  southeast  southwest
0   0.0  1.0        0.0        0.0        1.0
1   1.0  0.0        0.0        1.0        0.0
2   1.0  0.0        0.0        1.0        0.0
3   1.0  0.0        1.0        0.0        0.0
4   1.0  0.0        1.0        0.0        0.0

In [79]:
pd.concat([insurance_onehotencoded, oh_encoded_features], axis=1)

age     sex     bmi  children smoker     region      charges  male  yes  \
0      19  female  27.900         0    yes  southwest  16884.92400   0.0  1.0   
1      18    male  33.770         1     no  southeast   1725.55230   1.0  0.0   
2      28    male  33.000         3     no  southeast   4449.46200   1.0  0.0   
3      33    male  22.705         0     no  northwest  21984.47061   1.0  0.0   
4      32    male  28.880         0     no  northwest   3866.85520   1.0  0.0   
...   ...     ...     ...       ...    ...        ...          ...   ...  ...   
1333   50    male  30.970         3     no  northwest  10600.54830   1.0  0.0   
1334   18  female  31.920         0     no  northeast   2205.98080   0.0  0.0   
1335   18  female  36.850         0     no  southeast   1629.83350   0.0  0.0   
1336   21  female  25.800         0     no  southwest   2007.94500   0.0  0.0   
1337   61  female  29.070         0    yes  northwest  29141.36030   0.0  1.0   

      northwest  southeast  southwest  
0           0.0        0.0        1.0  
1           0.0        1.0        0.0  
2           0.0        1.0        0.0  
3           1.0        0.0        0.0  
4           1.0        0.0        0.0  
...         ...        ...        ...  
1333        1.0        0.0        0.0  
1334        0.0        0.0        0.0  
1335        0.0        1.0        0.0  
1336        0.0        0.0        1.0  
1337        1.0        0.0        0.0  

[1338 rows x 12 columns]

In [80]:
dropped_insurace_ohed = insurance_onehotencoded.drop(['sex', 'smoker', 'region'], axis=1)
dropped_insurace_ohed.head()

age     bmi  children      charges
0   19  27.900         0  16884.92400
1   18  33.770         1   1725.55230
2   28  33.000         3   4449.46200
3   33  22.705         0  21984.47061
4   32  28.880         0   3866.85520

In [81]:
pd.concat([dropped_insurace_ohed, oh_encoded_features], axis=1)

age     bmi  children      charges  male  yes  northwest  southeast  \
0      19  27.900         0  16884.92400   0.0  1.0        0.0        0.0   
1      18  33.770         1   1725.55230   1.0  0.0        0.0        1.0   
2      28  33.000         3   4449.46200   1.0  0.0        0.0        1.0   
3      33  22.705         0  21984.47061   1.0  0.0        1.0        0.0   
4      32  28.880         0   3866.85520   1.0  0.0        1.0        0.0   
...   ...     ...       ...          ...   ...  ...        ...        ...   
1333   50  30.970         3  10600.54830   1.0  0.0        1.0        0.0   
1334   18  31.920         0   2205.98080   0.0  0.0        0.0        0.0   
1335   18  36.850         0   1629.83350   0.0  0.0        0.0        1.0   
1336   21  25.800         0   2007.94500   0.0  0.0        0.0        0.0   
1337   61  29.070         0  29141.36030   0.0  1.0        1.0        0.0   

      southwest  
0           1.0  
1           0.0  
2           0.0  
3           0.0  
4           0.0  
...         ...  
1333        0.0  
1334        0.0  
1335        0.0  
1336        1.0  
1337        0.0  

[1338 rows x 9 columns]

## Ordinal encoding

In [82]:
from sklearn.preprocessing import OrdinalEncoder

In [83]:
insurance_ordinal.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [84]:
city = insurance_ordinal.region.unique()
city

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [85]:
oed = OrdinalEncoder(categories=[city])

In [86]:
oed_area = oed.fit_transform(insurance_ordinal[["region"]])
oed_area

array([[0.],
       [1.],
       [1.],
       ...,
       [1.],
       [0.],
       [2.]])

In [87]:
oed.categories_

[array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)]

In [88]:
insurance_ordinal.head(10)

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692

In [89]:
insurance_ordinal["region"] = oed_area
insurance_ordinal.head(10)

age     sex     bmi  children smoker  region      charges
0   19  female  27.900         0    yes     0.0  16884.92400
1   18    male  33.770         1     no     1.0   1725.55230
2   28    male  33.000         3     no     1.0   4449.46200
3   33    male  22.705         0     no     2.0  21984.47061
4   32    male  28.880         0     no     2.0   3866.85520
5   31  female  25.740         0     no     1.0   3756.62160
6   46  female  33.440         1     no     1.0   8240.58960
7   37  female  27.740         3     no     2.0   7281.50560
8   37    male  29.830         2     no     3.0   6406.41070
9   60  female  25.840         0     no     2.0  28923.13692